# Generated by Django 4.2.1 on 2023-07-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
