# Generated by Django 4.2.1 on 2023-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_order_tax_amount_order_tax_rate_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
    ]
