# Generated by Django 4.2.1 on 2023-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_bulkorder_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='tax_rate',
            field=models.FloatField(default=0.05),
        ),
    ]
