# Generated by Django 4.2.1 on 2023-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_bulkorder_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
