# Generated by Django 4.2.1 on 2023-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorder',
            name='delivery_charge',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
