# Generated by Django 4.2.1 on 2023-07-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_alter_bulkorder_delivery_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bulk_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.bulkorder'),
        ),
    ]
