# Generated by Django 4.2.1 on 2023-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_remove_order_transaction_transaction_bulk_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway_id',
            field=models.CharField(default=None),
        ),
    ]
