# Generated by Django 4.2.1 on 2023-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0010_alter_transaction_payment_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
