# Generated by Django 4.2.1 on 2023-07-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_product_piece_alter_product_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userside', '0011_alter_transaction_payment_gateway_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(max_length=25)),
                ('is_price_based', models.BooleanField(default=True)),
                ('offer_price', models.IntegerField(default=0, null=True)),
                ('offer_percentage', models.FloatField(default=0, null=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.product')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
