# Generated by Django 4.2.1 on 2023-07-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0012_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
