# Generated by Django 4.2.1 on 2023-07-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0013_delete_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userside.address'),
        ),
    ]
