# Generated by Django 4.2.1 on 2023-07-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('category_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='product/images')),
                ('image2', models.ImageField(upload_to='product/images')),
                ('image3', models.ImageField(upload_to='product/images')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=30)),
                ('sub_category_image', models.ImageField(upload_to='product/images')),
                ('sub_category_status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('product_label', models.CharField(max_length=45)),
                ('product_description', models.TextField()),
                ('product_status', models.BooleanField(default=False)),
                ('product_price', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('stock', models.IntegerField()),
                ('piece', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('total_energy', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
                ('product_image_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.productimage')),
                ('product_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subcategory')),
            ],
        ),
    ]
