# Generated by Django 4.2.1 on 2023-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_product_piece_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.BooleanField(default=True),
        ),
    ]
