# Generated by Django 4.2.1 on 2023-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_product_piece_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
