# Generated by Django 4.2.1 on 2023-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_product_expiry_date_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tax',
            field=models.FloatField(default=5.0),
        ),
    ]
